remote_theme: PfeifferChPT/pc-cdn-template
name: "PC-CDN"
title: "PC-CDN"
subtitle: "FONTS CDN"
description: "FONTS - Server | PC-CDN" #metadescription
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:title.html
excerpt_separator: <!--more-->
templateserverurl: https://template.pc-cdn.de
themecolor: dlt
themelogo: https://template.pc-cdn.de/assets/img/logo/logo.png
dummyimage: overlay-pattern.png
themeURI: https://template.pc-cdn.de/content/themes/writr/css/none.css
themeBGimage: none
GallerieDir: none
hbbhomeurl: none
livereload: true
author: Christian Pfeiffer
since: 2022
deactivaterelatedposts: true

# hostcredits: GHP (githubpages), IDN (IONOS DeployNow), OHI (Own Server)
# hostcredit: none
FAS: CSS
# FAS (Fontawesome): CSS (css File) JS (javascript) FASkit (Remote von kit.fontawesome.com)


defaults:
 - scope:
    path: "fonts"
   values:
    font: true
 - scope:
    path: "fontscnc"
   values:
    fontcnc: true

# Pagination Settings 
#pagination:
#  enabled: true
#  per_page: 2
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
